import type { CategoryContent } from '@/components/CategoryInfoModal'

export const categoryInfo: Record<string, CategoryContent> = {
	'AI Voice Agents': {
		sections: [
			{
				title: 'How AI phone agents will work',
				items: [
					'By the end of Phase 1 we will:',
					'• Let users create phone AI agents by hand',
					'• Let users also use AI to help set up these agents',
					'• Support both Inbound and Outbound AI phone agents',
					'',
					'For leads and call settings:',
					'• Users can add leads directly into the system',
					'• Users can set:',
					'  - How often to reach each lead',
					'  - During what hours to call',
					'  - How many leads per day',
					'  - How many calls at the same time',
					'',
					'For personalization:',
					'• Each lead can have small data fields, called variables',
					'• These variables can be filled by AI or filled by hand',
					'• These fields are sent to the AI agent during calls',
					'• This lets the agent talk in a more personal way',
					'',
					'For the phone system:',
					'• We use VAPI.ai in the background',
					'• When a user creates an agent:',
					'  - The agent is created inside VAPI through their API',
					'  - The settings, prompt and voice all live there also',
					'• Users can pick between voice providers that VAPI already uses',
					'• Users can also use ElevenLabs and custom voices',
					'',
					'For phone numbers:',
					'• Phone numbers will be added to VAPI with their API',
					'• We use the IDs and tokens that the user gives us',
					'',
					'For inbound calls:',
					'• Any incoming call can create or update a lead',
					'• That person is saved into the Leads Database',
				],
			},
			{
				title: 'Taking Control of Our Voice Technology',
				items: [
					'Right now, we\'re using VAPI, which acts as a middleman connecting us to voice technology providers. We\'re switching to connect directly with these providers ourselves, going straight to the source.',
					'',
					'We\'ll connect directly to:',
					'• TTS (text to speech)',
					'• STT (speech to text)',
					'• Realtime LLMs like GPT, Claude, and Gemini',
					'• WebRTC for handling calls',
					'',
					'This means:',
					'• Lower costs',
					'• Faster response times',
					'• Smoother conversations',
					'• Complete control over the experience',
					'',
					'We\'ll also connect phone numbers directly to this new system, giving us the freedom to create exactly what our users need.',
				],
			},
		],
	},
	'Scraping': {
		sections: [
			{
				title: 'Leads and B2B database',
				items: [
					'Lead upload:',
					'• Users can upload their own lead lists',
					'• These leads can be used by the AI agents for calls',
					'',
					'Our own lead database:',
					'• We will have our own built in lead database',
					'• Users can search for leads inside our database',
					'',
					'Real time scraping when needed:',
					'• If we do not have enough leads for a niche or industry, we will:',
					'  - Scrape new leads in real time from:',
					'    * Apollo',
					'    * LinkedIn Sales Navigator using PhantomBuster',
					'    * Google Maps using PhantomBuster or Apify',
					'• These new leads will:',
					'  - Go to the user who asked',
					'  - Also be added into our own database',
					'  - Be ready for future users who want leads from that space',
					'• We can run scraping daily in the background so:',
					'  - The lead database always grows over time',
					'  - Users get more and more ready leads to use',
				],
			},
		],
	},
	'AIs in the platform': {
		sections: [
			{
				title: 'AI inside the platform',
				items: [
					'There are three main AI parts inside the platform:',
					'',
					'After-call AI:',
					'• For each call we will:',
					'  - Save the full transcript',
					'  - Create a short summary',
					'  - Detect the main intent',
					'  - Capture key details on how the call went',
					'  - Update this info on that lead inside the CRM',
					'',
					'AI to help set up agents:',
					'• AI that helps users write prompts',
					'• AI that helps users set configurations for callers',
					'• This makes setup faster and less manual for users',
					'',
					'AI support chat in the corner:',
					'• A small chat bubble in the bottom right of the screen',
					'• AI can see and access all needed data for that user',
					'• Works like smart support inside the app',
					'• Example:',
					'  - If a user asks "What happened this week and what were the biggest complaints from customers"',
					'  - The AI:',
					'    * Reads call summaries',
					'    * Reads call transcripts',
					'    * Gives a clear answer based on real data',
					'',
					'To make this work we will:',
					'• Use large language models (LLMs) like GPT or Claude with their APIs',
					'• Use clear prompts and code to connect the AI to:',
					'  - The right data',
					'  - The database',
				],
			},
			{
				title: 'Business information and AI insights',
				items: [
					'Business information:',
					'• A place where users fill in details about their business by hand',
					'• AI cleans and reformats that text so it is clear and easy to use',
					'',
					'AI insights:',
					'• Another section where AI stores its own notes over time',
					'• AI makes observations about the business',
					'• These insights can be turned on for AI callers',
					'• When turned on, the callers can use this info inside their instructions',
				],
			},
		],
	},
	'Development': {
		sections: [
			{
				title: 'Tech setup',
				items: [
					'Where each part lives:',
					'',
					'User Interface (Frontend):',
					'• Deployed on Netlify or Vercel',
					'• This is the part users see and click',
					'',
					'Backend:',
					'• Deployed on Render',
					'• This holds the main "Agents" business logic',
					'• Handles user login and the link between screen, database and voice',
					'',
					'Database:',
					'• Supabase stores:',
					'  - User and organization data',
					'  - Agent configurations',
					'  - Customer profiles',
					'  - Call metadata',
					'',
					'Code and files:',
					'• Project files will live on GitHub or GitLab',
					'',
					'We expect to stay inside the normal limits of Render, Netlify, Supabase and others during Phase 1.',
					'We do not expect the need for enterprise pricing at this stage.',
				],
			},
			{
				title: 'Moving to AWS',
				items: [
					'We\'re moving the frontend, backend, and database to AWS (Amazon Web Services). Think of it like upgrading from a small office to a professional headquarters.',
					'',
					'This new infrastructure offers:',
					'• Stronger security',
					'• Better scalability',
					'• Can handle thousands more users while keeping everything running smoothly',
					'• A more robust foundation that grows with us',
					'',
					'Why not start with AWS from day one?',
					'• AWS is more complex and requires significantly more time and resources to set up properly',
					'• Our current providers handle many technical tasks automatically that we\'d need to build ourselves on AWS',
					'• By starting with simpler providers, we can launch our MVP faster, prove the product works, and validate that people truly want it, without burning through time and budget on complex infrastructure',
					'• Once we\'ve proven demand and gained traction, migrating to AWS makes sense',
				],
			},
			{
				title: 'Enterprise Grade API integration',
				items: [
					'We\'re adding enterprise-grade APIs that let our users link our system with the other software they already use.',
					'',
					'Whatever apps or systems they\'re running, everything can now talk to each other and stay in sync automatically.',
				],
			},
		],
	},
	'Chatbots': {
		sections: [
			{
				title: 'AI Omnichannel Chat',
				items: [
					'The user can create chat agents for their website.',
					'',
					'This AI will be built to handle unlimited customer tickets, 24/7.',
					'',
					'We will enable it to:',
					'• Help customers find products',
					'• Offer discount codes',
					'• Convert visitors into buyers',
					'',
					'Connects with the leads list.',
					'',
					'Similar to the Phone Agents, the user can create this manually or with the help of AI.',
					'',
					'We will allow agents to perform tasks like:',
					'• Sending an SMS',
					'• Checking calendar availability',
				],
			},
		],
	},
}

